const productsData = [
  {
    id: 1,
    title: 'Patterned jersey shorts',
    category: 'kids',
    price: 2.99,
    img: './images/kids4.jpg',
  },
  {
    id: 2,
    title: 'Cotton shirt',
    category: 'kids',
    price: 2.99,
    img: './images/kids7.jpg',
  },
  {
    id: 3,
    title: 'Cropped sweater vest',
    category: 'women',
    price: 3.99,
    img: './images/women1.jpg',
  },
  {
    id: 4,
    title: 'Linen suit trousers Slim Fit',
    category: 'men',
    price: 5.99,
    img: './images/men1.jpg',
  },
  {
    id: 5,
    title: '4-piece cotton set',
    category: 'kids',
    price: 2.99,
    img: './images/kids2.jpg',
  },
  {
    id: 6,
    title: 'Boyfriend High Waist',
    category: 'women',
    price: 2.99,
    img: './images/women2.jpg',
  },
  {
    id: 7,
    title: 'Oversized T-shirt',
    category: 'men',
    price: 2.99,
    img: './images/men2.jpg',
  },
  {
    id: 8,
    title: '2-pack printed T-shirts',
    category: 'kids',
    price: 2.99,
    img: './images/kids6.jpg',
  },
  {
    id: 9,
    title: 'T-shirt with a motif',
    category: 'men',
    price: 2.99,
    img: './images/men3.jpg',
  },
  {
    id: 10,
    title: '3-pack bow-detail strappy tops',
    category: 'kids',
    price: 2.99,
    img: './images/kids3.jpg',
  },
  {
    id: 11,
    title: 'Denim skirt',
    category: 'women',
    price: 2.99,
    img: './images/women3.jpg',
  },
  {
    id: 12,
    title: 'Super Soft Slim Fit Shorts',
    category: 'kids',
    price: 2.99,
    img: './images/kids8.jpg',
  },
  {
    id: 13,
    title: 'Balloon-sleeved dress',
    category: 'women',
    price: 2.99,
    img: './images/women4.jpg',
  },
  {
    id: 14,
    title: 'Text-print T-shirt',
    category: 'men',
    price: 2.99,
    img: './images/men4.jpg',
  },
  {
    id: 15,
    title: '2-pack cotton T-shirts',
    category: 'kids',
    price: 2.99,
    img: './images/kids5.jpg',
  },
  {
    id: 16,
    title: 'Balloon-sleeved dress',
    category: 'women',
    price: 2.99,
    img: './images/women5.jpg',
  },
  {
    id: 17,
    title: 'Stretch shirt Slim Fit',
    category: 'men',
    price: 2.99,
    img: './images/men5.jpg',
  },
  {
    id: 18,
    title: 'Patterned jersey shorts',
    category: 'kids',
    price: 2.99,
    img: './images/kids1.jpg',
  },
  {
    id: 19,
    title: 'Puff-sleeved dress',
    category: 'women',
    price: 2.99,
    img: './images/women6.jpg',
  },
  {
    id: 20,
    title: 'Short-sleeve shirt Regular fit',
    category: 'men',
    price: 2.99,
    img: './images/men6.jpg',
  },
  {
    id: 21,
    title: 'Voluminous resort shirt',
    category: 'women',
    price: 2.99,
    img: './images/women7.jpg',
  },
  {
    id: 22,
    title: '2-pack Regular Fit sweatshorts',
    category: 'men',
    price: 2.99,
    img: './images/men7.jpg',
  },
  {
    id: 23,
    title: 'Ribbed jersey dress',
    category: 'women',
    price: 2.99,
    img: './images/women8.jpg',
  },
  {
    id: 24,
    title: 'Regular Denim shorts',
    category: 'men',
    price: 2.99,
    img: './images/men8.jpg',
  },
];
export default productsData;
